"""empty message

Revision ID: 29f4bda931ab
Revises: 43b68933be5e
Create Date: 2015-01-27 13:08:37.163000

"""

# revision identifiers, used by Alembic.
revision = '29f4bda931ab'
down_revision = '43b68933be5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
