"""empty message

Revision ID: 43b68933be5e
Revises: 4e1a3b8be933
Create Date: 2015-01-27 12:49:15.597000

"""

# revision identifiers, used by Alembic.
revision = '43b68933be5e'
down_revision = '4e1a3b8be933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('created_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'created_on')
    ### end Alembic commands ###
